CREATE TABLE `dimensionamento` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome` varchar(255) NOT NULL,
	`login` varchar(128),
	`loginOlos` int,
	`email` varchar(320),
	`supervisor` varchar(128),
	`admissao` varchar(32),
	`nascimento` varchar(32),
	`cpf` varchar(32),
	`funcao` varchar(255),
	`cargo` varchar(128),
	`departamento` varchar(128),
	`uf` varchar(8),
	`status` varchar(32) DEFAULT 'ATIVO',
	`discador` varchar(64),
	`celula` varchar(128),
	`skill` varchar(255),
	`turno` varchar(32),
	`escalaHora` varchar(16),
	`escala` varchar(32),
	`entrada` varchar(16),
	`saida` varchar(16),
	`entradaS` varchar(16),
	`saidaS` varchar(16),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dimensionamento_id` PRIMARY KEY(`id`)
);
